pages/30_Bilan_Mediatree.py
pages/4_Exploration_Siteweb_Media.py
quotaclimat/data_analytics/bilan.py

Adding the temporal evolution. I had to split radio and TV as the coverage is different in high audience hours (2 hours TV and 4 hours radio). We can do that in a better way, though Eva needs the results tonight for the communiqué de presse

feat: add evolution over time

---

README.md

Update README.md for poetry on Windows

---

.streamlit/secrets.toml
pages/5_Exploration_Siteweb.py
postgres/create_tables.py
postgres/insert_existing_data_example.py
postgres/schemas/sitemap.pgsql
quotaclimat/data_analytics/bilan.py
quotaclimat/data_analytics/sitemap_analytics.py
quotaclimat/data_processing/sitemap/queries.py

POC: Plugged some figures to the data from the db.
I merge it to see if it runs properly with streamlit cloud

feat: poc queries in sql

---

pages/5_Exploration_des_titres_d'articles.py
quotaclimat/data_analytics/sitemap_analytics.py
quotaclimat/data_ingestion/scrap_sitemap.py

The tool to compare frequencies of the keyword of two list is now leveraging the data from the db.
The groupby still need to be migrated from pandas to sql

feat: keywords comparisons are leveraging the db

---

.github/workflows/deploy-main.yml
.gitignore
Dockerfile_api_import
README.md
docker-compose.yml
postgres/insert_data.py
postgres/schemas/models.py
quotaclimat/data_processing/mediatree/api_import.py
quotaclimat/data_processing/mediatree/keyword/keyword.py
quotaclimat/data_processing/mediatree/utils.py
test/sitemap/test_mediatree.py
test/sitemap/test_mediatree_utils.py
test/sitemap/utils.py

https://keywords.mediatree.fr/docs/
Contact QuotaClimat team to 2 files with the API's username and password inside : 
* secrets/pwd_api.txt
* secrets/username_api.txt
```
docker compose up mediatree
```

Data: import API

---

.github/workflows/deploy-main.yml
quotaclimat/data_processing/mediatree/keyword/keyword.py
test/sitemap/test_mediatree.py

Ajout des thématiques :
* adaptation
* atténuation
Changement des noms pour plus de cohérences des autres thèmes : 
* THEME_consequences
* THEME_causes
* THEME_solutions
* THEME_constat
Exemple : changement_climatique_constat

feat: more keywords to categorize by theme

---

postgres/insert_data.py
postgres/schemas/models.py

Fix this error due to altering the column type in Postgres, it's easier to query like this
```
column "theme" is of type json but expression is of type text[]
```

fix: array to json for theme

---

.github/workflows/test.yml
docker-compose.yml

https://github.com/MishaKav/pytest-coverage-comment
https://pytest-cov.readthedocs.io/en/latest/config.html

Configure: test coverage

---

README.md
docker-compose.yml
poetry.lock
pyproject.toml
quotaclimat/data_processing/mediatree/api_import.py
quotaclimat/data_processing/mediatree/utils.py
test/sitemap/test_mediatree.py
test/sitemap/test_mediatree_utils.py

Batch import based on env variable `START_DATE` epoch in second, if it's not there we use default yesterday epoch.
Performance:
* dataframe apply is slow so we should use https://github.com/jmcarpenter2/swifter
Reliability on 500 errors from Mediatree api : 
* Be able to retry in case of error without failing (https://github.com/jd/tenacity/tree/main)

Feat: batch import + retry on API errors

---

poetry.lock
quotaclimat/data_processing/mediatree/api_import.py
quotaclimat/data_processing/mediatree/utils.py
test/sitemap/test_mediatree.py
test/sitemap/test_mediatree_utils.py

use parameter `from` (Starting point from index of the hits) from the API to not miss any data

Feat/pagination - use from parameter

---

quotaclimat/data_ingestion/ingest_db/ingest_sitemap_in_db.py
quotaclimat/data_processing/mediatree/api_import.py

Monitore cron execution on scaleway and alert on slack on non execution: https://docs.sentry.io/platforms/python/crons/

Monitoring: sentry cron on scaleway

---

quotaclimat/data_ingestion/ingest_db/ingest_sitemap_in_db.py
quotaclimat/data_processing/mediatree/api_import.py

Cron duration is missing when using as a decorator, passing the context now:
From : https://docs.sentry.io/platforms/python/crons/#job-monitoring

monitor: cron duration with sentry

---

docker-compose.yml
quotaclimat/data_processing/mediatree/detect_keywords.py
quotaclimat/data_processing/mediatree/update_pg_keywords.py
quotaclimat/data_processing/mediatree/utils.py
test/sitemap/test_detect_keywords.py
test/sitemap/test_main_import_api.py
test/sitemap/test_mediatree_utils.py
test/sitemap/test_update_pg_keywords.py

Before: we count from the first appearance of a keyword and 15 second window based on keywords
After: we count from the 2 minute chunk "start" column with 15 second windows

feat: number of keywords based on 15 sec window

---

quotaclimat/data_processing/mediatree/detect_keywords.py
test/sitemap/test_detect_keywords.py

Edge cases where keyword timestamp is above 8th window

fix: edge cases fifteen second window

---

.github/workflows/test.yml
README.md

Based on https://github.com/MishaKav/pytest-coverage-comment/blob/main/.github/workflows/live-test.yml and  https://github.com/Schneegans/dynamic-badges-action

Readme : test badge

---

quotaclimat/data_processing/mediatree/api_import.py
quotaclimat/data_processing/mediatree/detect_keywords.py
test/sitemap/test_detect_keywords.py

Some cases after the 2 minute mark should be counted

Fix: fifteen second window count edge cases really close to the 2 minute chunk 

---

postgres/insert_data.py
postgres/schemas/models.py
quotaclimat/data_processing/mediatree/detect_keywords.py
test/sitemap/test_detect_keywords.py

feat(data): save srt to replay data

---

docker-compose.yml
postgres/schemas/models.py
quotaclimat/data_processing/mediatree/keyword/keyword.py
test/sitemap/test_detect_keywords.py
test/sitemap/test_main_import_api.py

New udpdate
Store it inside a new temporary table to compare `keywords_new_list`

Update keywords list

---

quotaclimat/data_processing/mediatree/api_import.py

Handle 401 case from API
Needs to improve this part https://github.com/jd/tenacity/tree/main?tab=readme-ov-file#error-handling

fix: refresh token on 401

---

.github/workflows/deploy-main.yml
.github/workflows/test.yml
Dockerfile
Dockerfile_api_import
Dockerfile_ingest
Dockerfile_streamlit
poetry.lock
quotaclimat/data_processing/mediatree/api_import.py
quotaclimat/data_processing/mediatree/detect_keywords.py
quotaclimat/data_processing/mediatree/keyword/keyword.py
test/sitemap/test_detect_keywords.py
test/sitemap/test_main_import_api.py
test/sitemap/test_mediatree.py

chores: update keywords list + channel france24/

---

quotaclimat/data_processing/mediatree/api_import.py
quotaclimat/data_processing/mediatree/detect_keywords.py
quotaclimat/data_processing/mediatree/update_pg_keywords.py
test/sitemap/test_update_pg_keywords.py

Bonus: Stop modin debug logging with a dirty line of code

fix(memory): update by batch instead of a get all

---

postgres/insert_data.py
postgres/schemas/models.py
quotaclimat/data_processing/mediatree/detect_keywords.py
quotaclimat/data_processing/mediatree/keyword/keyword.py
quotaclimat/data_processing/mediatree/update_pg_keywords.py
test/sitemap/test_detect_keywords.py
test/sitemap/test_update_pg_keywords.py

https://github.com/dataforgoodfr/quotaclimat/issues/113
Apply count to these columns to create number_of_$THEME
-                  'number_of_changement_climatique_constat',
-                  'number_of_changement_climatique_causes_directes',
-                  'number_of_changement_climatique_consequences',
-                  'number_of_attenuation_climatique_solutions_directes',
-                  'number_of_adaptation_climatique_solutions_directes',
-                  'number_of_ressources_naturelles_concepts_generaux',
-                  'number_of_ressources_naturelles_causes',
-                  'number_of_ressources_naturelles_solutions',
-                  'number_of_biodiversite_concepts_generaux',
-                  'number_of_biodiversite_causes_directes',
- …

feat: count THEME

---

README.md
docker-compose.yml
quotaclimat/data_processing/mediatree/api_import.py
test/sitemap/test_mediatree.py

New channel added
Improve error handler for wrong channel name

feat: new channel france info radio

---

docker-compose.yml
pyproject.toml
quotaclimat/data_processing/mediatree/detect_keywords.py
quotaclimat/data_processing/mediatree/keyword/keyword.py
quotaclimat/data_processing/mediatree/keyword/stop_words.py
test/sitemap/test_detect_keywords.py
test/sitemap/test_update_pg_keywords.py

New stop word: en train d
does not count ressources as it's not ready yet
update keywords list

chores: new stop work + update keywords list + does not count ressources as it's not ready yet

---

quotaclimat/data_processing/mediatree/detect_keywords.py
quotaclimat/data_processing/mediatree/update_pg_keywords.py
test/sitemap/test_detect_keywords.py
test/sitemap/test_update_pg_keywords.py

Lors de grosse MAJ, certains mots clés enlévés laissent des null dans la base de données
Cette PR les supprimer plutôt que de mettre à jour à null

fix: delete row where there is no more theme (deleted keywords case)

---

Dockerfile
README.md
docker-compose.yml
poetry.lock
pyproject.toml
quotaclimat/data_processing/mediatree/api_import.py
quotaclimat/data_processing/mediatree/channel_program.json
quotaclimat/data_processing/mediatree/channel_program.py
quotaclimat/data_processing/mediatree/detect_keywords.py
quotaclimat/data_processing/mediatree/update_pg_keywords.py
test/sitemap/test_detect_keywords.py

Refactoring pour modin - ray
S'assurer de la timezone lors de la comparaison program/subtitle lors la mise à jour (UPDATE=true)
Possibilité de mettre seulement à jour les colonnes program_channel et program_channel_type via `UPDATE_PROGRAM_ONLY=true`
Fix: bug lorsqu'un programme commence et termine à la même heure qu'un autre qui commence

Fix: update program metadata

---

Dockerfile
Dockerfile_api_import
README.md
docker-entrypoint.sh
postgres/program_metadata.json
transform_program.py

Ops: improve program metadata table management by automated the generation process

refacto: automate transform program metadata

---

quotaclimat/data_processing/mediatree/api_import.py

Crash on main function didn't have proper exit code, now it does. Enable cron jobs to see failures with more accurency

fix: gracefully shutdown on crash

---

README.md
docker-compose.yml
poetry.lock
pyproject.toml
quotaclimat/data_processing/mediatree/api_import.py
quotaclimat/data_processing/mediatree/channel_program.py
quotaclimat/data_processing/mediatree/update_pg_keywords.py
test/sitemap/test_update_pg_keywords.py

Fix: logging.error for update
Feat:
We can adjust batch update with these env variables (as in the docker-compose.yml): 
```
BATCH_SIZE: 50000 # number of records to update in one batch
NUMBER_OF_BATCH: 4 # number of batch size to process
```

feat: update - use number_of_batch - add channel_title if missing

---

docker-compose.yml
quotaclimat/data_processing/mediatree/channel_program.py
quotaclimat/data_processing/mediatree/detect_keywords.py
test/sitemap/test_detect_keywords.py

Add tests for different windows
Fix a filter

Fix: window duration for 20/30/40

---

docker-compose.yml
poetry.lock
pyproject.toml
quotaclimat/data_processing/mediatree/channel_program.json
quotaclimat/data_processing/mediatree/channel_program.py
quotaclimat/data_processing/mediatree/update_pg_keywords.py
test/sitemap/test_program_metadata.py
transform_program.py

https://modin.readthedocs.io/en/stable/getting_started/troubleshooting.html#importing-heterogeneous-data-using-read-csv
```
2024-06-19 15:57:51.440	
Data types of partitions are different! Please refer to the troubleshooting section of the Modin documentation to fix this issue.
2024-06-19 15:57:51.440	
UserWarning: `read_*` implementation has mismatches with pandas:
```

refacto: modin has problem with multiple type for same column

---

README.md
poetry.lock
pyproject.toml
quotaclimat/data_processing/mediatree/keyword/keyword.py
quotaclimat/data_processing/mediatree/keyword/stop_words.py
test/sitemap/test_detect_keywords.py
test/sitemap/test_main_import_api.py
test/sitemap/test_update_pg_keywords.py
transform_excel_to_json.py

1000+  to 1750 words
From channels feedbacks
Improve excel to json script

chores: update dict

---

.github/workflows/test.yml

Coverage generation used to crash dependat bot CI : https://github.com/dataforgoodfr/quotaclimat/actions/runs/9738467627/job/26872109168?pr=198

fix ci: dependat bot

---

quotaclimat/data_processing/mediatree/api_import.py

RAM not being freed after a while, pandas/modin issue ?

prod: garbage collector after loop

---

quotaclimat/data_processing/mediatree/api_import.py
quotaclimat/data_processing/mediatree/detect_keywords.py
test/sitemap/test_main_import_api.py

```could not broadcast input array from shape (2,) into shape (1,) with df  ```
Same error as #217 but in another spot 
Only happens for some channels

fix: use apply for id

---

.gitignore
poetry.lock
pyproject.toml
quotaclimat/data_processing/mediatree/api_import.py
quotaclimat/data_processing/mediatree/keyword/keyword.py

data quality check with categories

review: keywords category

---

quotaclimat/data_processing/mediatree/detect_keywords.py

Removing deepcopy for best practices and #237

refacto: remove deepcopy to fix memory leak

---

quotaclimat/data_processing/mediatree/channel_program.py
quotaclimat/data_processing/mediatree/utils.py

fix: program name can be null when margin is not enough

---

README.md
quotaclimat/data_processing/mediatree/api_import.py
test/sitemap/test_mediatree.py

Mediatree api does not normalize channel title (but only channel name)

Data quality: normalize channel title 

---

quotaclimat/data_processing/mediatree/detect_keywords.py
quotaclimat/data_processing/mediatree/keyword/stop_words.py
quotaclimat/data_processing/mediatree/stop_word/main.py
test/sitemap/test_keywords.py

Order is important for the stop word list as if we remove some stop word before other, it will affect the context of the said stop word.
Now : 
* we get all stop word ordered by count,
* add a special case for some advertisers
* remove MEDIATREE_TRANSCRIPTION_PROBLEM = "<unk> "

feat: stop list ordered by count desc, special case for big advertiser

---

test/sitemap/light.json
test/sitemap/test_main_import_api.py

https://github.com/dataforgoodfr/quotaclimat/issues/309
Tests Execution time from 9 minutes to 3 minutes :heavy_check_mark:

refacto: test with a tiny file instead of 15Mb file

---

quotaclimat/data_processing/mediatree/update_pg_keywords.py
test/sitemap/test_update_pg_keywords.py
test/stop_word/test_stop_word.py

https://github.com/dataforgoodfr/quotaclimat/issues/321

fix(stop_word): case where keyword is empty to enable faster updates filter

---

quotaclimat/data_processing/mediatree/api_import.py

Change based on this production logs
```
WARNING - api_import.py:143 | Delay detected : 1 days
```

fix(security_nets): normal delay should be 1 day and not 0

---

README.md
docker-entrypoint.sh
my_dbt_project/models/homepage/homepage_environment_by_media_by_month.sql

To be sure our views get refreshed, we use dbt run on a cron inside our docker image

cd: view to refresh via deployment using dbt run

---

postgres/insert_data.py
postgres/schemas/models.py
quotaclimat/data_ingestion/ingest_db/ingest_sitemap_in_db.py
quotaclimat/data_processing/mediatree/api_import.py
quotaclimat/data_processing/mediatree/s3/api_to_s3.py
quotaclimat/data_processing/mediatree/stop_word/main.py
quotaclimat/data_processing/mediatree/update_pg_keywords.py
test/mediatree/test_mediatree_queries.py
test/sitemap/test_main_import_api.py
test/sitemap/test_mediatree.py
test/sitemap/test_update_pg_keywords.py
test/stop_word/test_stop_word.py

Dev PK was not the same as production PK, and upsert did not work there. This PR fix the PK in dev docker and make the app crash on saving errors

fix: upsert with the right PK

---

.github/workflows/deploy-main.yml
.github/workflows/test.yml
Dockerfile
Dockerfile_api_import
Dockerfile_api_to_s3
Dockerfile_ingest
Dockerfile_stop_word
docker-entrypoint.sh

DBT models should be executed after our data has been calculated

refacto: dbt model after job + poetry bump

---

my_dbt_project/dbt_project.yml
my_dbt_project/models/dashboards/core_query_thematics_keywords.sql
my_dbt_project/pytest_tests/test_dbt_model_homepage.py
my_dbt_project/seeds/dictionary.csv

#356 
will add these column : 
-             high_risk_of_false_positive,
-             solution,
-             consequence,
-             cause,
-             general_concepts,
-             statement,
-             crisis_climate,
-             crisis_biodiversity,
-             crisis_resource,
-             categories,
-             themes,
-             language

refacto: add join on dictionary table to normalize keyword metadata

---

docker-compose.yml
my_dbt_project/models/dashboards/core_query_thematics_keywords.sql
my_dbt_project/pytest_tests/test_dbt_model_homepage.py

Categories should come from dictionary table :
- a row for each category of a keyword

fix(dbt): category are up-to-date with dictionary table and not keywords_with_timestamp

---

my_dbt_project/models/homepage/homepage_environment_by_media_by_month.sql

fix: dbt filtre france

---

quotaclimat/data_processing/mediatree/i8n/country.py

fix: add missing channels belgium

---

quotaclimat/data_processing/mediatree/stop_word/main.py

fix: Main crash (NameError) name 'country' is not defined

fix(stopwords): use proper country variable

---

my_dbt_project/models/dashboards/core_query_thematics_keywords.sql

another country filter was forgotten

fix: add country filter to views keywords

---

i8n/srt-to-mediatree-format-parquet.py

#https://docs.sentry.io/platforms/python/crons/

chores: add srt monitoring

---

my_dbt_project/models/dashboards/core_query_thematics_keywords.sql
my_dbt_project/pytest_tests/test_dbt_model_homepage.py

bug introduced in https://github.com/dataforgoodfr/quotaclimat/pull/362

fix: remove unnecessary group by element introduced in #362
