dataforgoodfr/quotaclimat

.github/workflows/check_integration.yml
This ensures the `.toml` is aligned with the `.lock` (so that the environment can be build when deploying). This is the first integration test. More can be added in the same/copy-pasted workflow.
=> feat: add integration test at push

.gitignore, docker-compose.yml, postgres/insert_data.py, postgres/schemas/models.py, quotaclimat/data_ingestion/scrap_homepage_lemonde/scrap_homepage.py, quotaclimat/data_processing/mediatree/api_import.py, quotaclimat/data_processing/mediatree/keyword/keyword.py, test/sitemap/test_mediatree.py
Pour avoir plus de visibilité sur la données stockées (basé sur la présence ou non de mot clé), on rajoute ici 2 champs dans la base : 
* le mot clé 
* et son timecode
dans un seul champs `keywords_with_timestamp` 
* ajout du champs `number_of_keywords` pour compter directement à l'ecriture et faciliter le requetâge
Ce champs est fabriqué à partir du champs `srt` de l'API mediatree
* pluriel et singulier (voiture et voitures) en utilisant seulement le mot clé singulier voiture
* prise en compte de l'espace lors de l'utilisation de quote (')
```
"start": 1704798000,
"plaintext":  "VACHE BOVIN Anthropocène",
"channel_name": "m6",
"channel_radio": False,
"theme": [
"changement_climatique_constat",
"changement_climatique_causes_indirectes",
"ressources_naturelles_concepts_generaux"
]
```
``` …
```
=> Feat(data): add keyword with timestamp + improve keywords detection 

docker-compose.yml, postgres/insert_data.py, quotaclimat/data_processing/mediatree/api_import.py, quotaclimat/data_processing/mediatree/keyword_processor.py, quotaclimat/data_processing/mediatree/utils.py, test/sitemap/test_mediatree_utils.py
La pagination par "from" ne marche pas, cette PR propose d'utiliser les bons vieux 
- start_gte Start date greater or equal than (GTE), allowed format epoch and YYYY-MM-DDTHH:MM:SS
- start_lte : Start date greater or equal than (GTE), allowed format epoch and YYYY-MM-DDTHH:MM:SS
Avec une fréquence de une requete toutes les 12 heures
=> fix: use date gte lte instead of page

.github/workflows/deploy-main.yml
Scaleway can have cache problem on their docker registry, so i force the tag to the app version instead of latest
:warning: docker registry size
=> CD: docker image set PROJECT_VERSION instead of always latest

README.md, docker-compose.yml, quotaclimat/data_processing/mediatree/api_import.py, test/sitemap/test_mediatree.py
Use env variable `CHANNEL` like in docker compose (string: tf1)
Otherwise, default is all channels
=> feat: import only one channel based on var env

docker-compose.yml, poetry.lock, postgres/database_connection.py, pyproject.toml, quotaclimat/data_processing/mediatree/api_import.py, quotaclimat/data_processing/mediatree/detect_keywords.py, quotaclimat/data_processing/mediatree/update_pg_keywords.py, quotaclimat/data_processing/mediatree/utils.py, test/sitemap/test_detect_keywords.py, test/sitemap/test_main_import_api.py, test/sitemap/test_mediatree.py, test/sitemap/test_update_pg_keywords.py
Pandas is single core and does not scale, we should use Modin
https://modin.readthedocs.io/en/latest/getting_started/why_modin/pandas.html
=> Perf: Pandas modin lib

postgres/schemas/models.py
Back to the original name after test
First command
```
DROP TABLE keywords;
```
Second command
```
ALTER TABLE keywords_new_list
RENAME TO keywords; 
```
=> Chores: rename table keywords

quotaclimat/data_ingestion/ingest_db/ingest_sitemap_in_db.py
Migrate to Jobs instead of Containers to remove the 15 minutes sleep to exit gracefully
=> chores(scaleway): remove delay for sitemap

.github/workflows/scaleway-down.yml, .github/workflows/scaleway-start-import-job-update.yml, .github/workflows/scaleway-up.yml, README.md, docker-compose.yml, postgres/insert_data.py, quotaclimat/data_processing/mediatree/api_import.py, quotaclimat/data_processing/mediatree/update_pg_keywords.py, quotaclimat/data_processing/mediatree/utils.py, test/sitemap/test_main_import_api.py, test/sitemap/test_mediatree_utils.py, test/sitemap/test_update_pg_keywords.py
Plus pour les humains, on utilise maintenant la date de debut de MAJ plutôt que l'offset
---
With +1 millions rows, we can update from an offset to fix a custom logic by using `START_DATE_UPDATE` (YYYY-MM-DD), the default will use the end of the month otherwise you can specify`END_DATE` (optional) (YYYY-MM-DD) to batch update PG from a date range.
~55 minutes to update 50K rows on a mVCPU 2240 - 4Gb RAM on Scaleway.
Every month has ~80K rows.
Example inside the docker-compose.yml mediatree service -> START_DATE_UPDATE: 2024-04-01 - default END_DATE will be 2024-04-30
We can use [a Github actions to start multiple update operations with different date, set it using the matrix](https://github.com/dataforgoodfr/quotaclimat/blob/main/.github/workflows/scaleway-start-import-job-update.yml)
=> feat(update): use start_date instead of start_offset

docker-compose.yml, quotaclimat/data_processing/mediatree/api_import.py
```
ERROR - api_import.py:186 | Retry - get_df_api:(ValueError) could not broadcast input array from shape (2,) into shape (1,)
```
=> Log: fix error array from shape (2,) into shape (1,)

quotaclimat/data_processing/mediatree/api_import.py
=> refacto: dataframe loop with itertuples to spot memory leak

quotaclimat/data_processing/mediatree/api_import.py, quotaclimat/data_processing/mediatree/channel_program.py, quotaclimat/data_processing/mediatree/update_pg_keywords.py, quotaclimat/data_processing/mediatree/utils.py, test/sitemap/test_program_metadata.py
Lors de l'import des données de l'API mediatree, nous prenons +5 minutes avant et après le programme pour être généreux sur les imports
Les MAJ (avec `UPDATE=true`) ne prennaient pas en compte cette marge, et les programmes avec les marges se retrouvaient avec leur champs programmes vides.
Cette PR fix cela
=> fix: use margin when updating program name

README.md, quotaclimat/data_processing/mediatree/api_import.py, quotaclimat/data_processing/mediatree/update_pg_keywords.py, test/sitemap/test_update_pg_keywords.py
Faster updates with : 
`UPDATE_PROGRAM_CHANNEL_EMPTY_ONLY` to true will only update program metadata with empty value : "".
=> feat: update only empty program

quotaclimat/data_processing/mediatree/detect_keywords.py, quotaclimat/data_processing/mediatree/utils.py, test/sitemap/test_detect_keywords.py
Pour une meilleure lisibilité, changement de nom de variables autour de la valeur du temps de découpage en 20 secondes. Il y restait quelques 15 secondes mais non utilisés car overwritte par 20
=> refacto: change variable name from fifteen to twenty

quotaclimat/data_processing/mediatree/detect_keywords.py, quotaclimat/data_processing/mediatree/keyword/keyword.py, test/sitemap/test_detect_keywords.py, test/sitemap/test_main_import_api.py, transform_excel_to_json.py
A any direct word could transform a high risk of false positive
A direct word can only contaminate a high risk of false positive if it has the same subject: climate/ biodiversity/ressource
=> Fix: only transform false positive when keyword has the same subject

.github/workflows/deploy-main.yml, .gitignore, Dockerfile_api_to_s3, README.md, docker-compose.yml, poetry.lock, pyproject.toml, quotaclimat/data_processing/mediatree/s3/api_to_s3.py, test/s3/test_s3.py
Save Mediatree data as a security nets to S3 scaleway
Tasks:
=> feat: api to s3

quotaclimat/data_processing/mediatree/s3/api_to_s3.py, quotaclimat/data_processing/mediatree/utils.py
to have a safety nets, check the previous 7 days if there is missing data and reimport if missing
=> refacto: api-to-s3 :default time from 1 to 7

README.md, docker-compose.yml, quotaclimat/data_processing/mediatree/api_import.py, quotaclimat/data_processing/mediatree/s3/api_to_s3.py, quotaclimat/data_processing/mediatree/utils.py, test/sitemap/test_mediatree_utils.py
* Sentry cron monitor for api-to-s3
* Date management 
1. feat : mediatree import : can specify how many days we want to query thanks to `NUMBER_OF_PREVIOUS_DAYS` : int default with 30
2. fix : api-to-s3 - security nets with `NUMBER_OF_PREVIOUS_DAYS` : int default with 7
=> fix: date import - cron monitor

quotaclimat/data_processing/mediatree/api_import.py, quotaclimat/data_processing/mediatree/s3/api_to_s3.py, quotaclimat/data_processing/mediatree/utils.py, test/sitemap/test_mediatree_utils.py
fix `int() argument must be a string, a bytes-like object or a real number, not 'NoneType'`
=> fix: default to 0 when missing value for start date

README.md, quotaclimat/data_processing/mediatree/api_import.py, quotaclimat/data_processing/mediatree/s3/api_to_s3.py, quotaclimat/data_processing/mediatree/utils.py
Default value to 1 days for NUMBER_OF_PREVIOUS_DAYS for mediatree job, and 7 for api-to-s3
=> refacto: NUMBER_OF_PREVIOUS_DAYS

.github/workflows/deploy-main.yml, README.md, docker-compose.yml, quotaclimat/data_processing/mediatree/api_import.py, quotaclimat/data_processing/mediatree/detect_keywords.py, quotaclimat/data_processing/mediatree/keyword/stop_words.py, quotaclimat/data_processing/mediatree/s3/api_to_s3.py, quotaclimat/data_processing/mediatree/stop_word/main.py, quotaclimat/data_processing/mediatree/update_pg_keywords.py, quotaclimat/data_processing/mediatree/utils.py, test/sitemap/test_detect_keywords.py, test/sitemap/test_keywords.py, test/sitemap/test_main_import_api.py, test/sitemap/test_mediatree_utils.py, test/stop_word/test_stop_word.py
Enable new job that will update keywords every week based on new stop words/keywords
=> Feat/api import/update use stop word table

docker-compose.yml, poetry.lock, pyproject.toml, quotaclimat/data_processing/mediatree/s3/api_to_s3.py, quotaclimat/data_processing/mediatree/utils.py, test/s3/test_s3.py, test/sitemap/test_mediatree_utils.py
fix error from bumping boto3 version, force "s3transfer = "0.10.4" to solve it 
```
An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method
```
Plus add better log error and test for get date range default case
=> fix: downgrade boto version - explicite errors

README.md, quotaclimat/data_processing/mediatree/stop_word/main.py
* CONTEXT_TOTAL_LENGTH (integer) : default 80 - the length of the advertising context (sentence) saved
=> feat: configure context length

README.md, quotaclimat/data_processing/mediatree/detect_keywords.py, quotaclimat/data_processing/mediatree/stop_word/main.py, test/sitemap/test_keywords.py, test/sitemap/test_update_pg_keywords.py, test/stop_word/test_stop_word.py
https://github.com/dataforgoodfr/quotaclimat/issues/326
=> feat: improve ad detection with normalization

README.md, quotaclimat/data_processing/mediatree/api_import.py, quotaclimat/data_processing/mediatree/api_import_utils/db.py, quotaclimat/data_processing/mediatree/update_pg_keywords.py, quotaclimat/data_processing/mediatree/utils.py, test/mediatree/test_mediatree_queries.py, test/sitemap/test_main_import_api.py, test/sitemap/test_update_pg_keywords.py
As Scaleway Serverless service can be down, if some dates are missing until today, it will start back from the latest date saved until today.
In case the production goes down for several days, it will catch up automatically the delay instead of starting manual importing jobs
=> feat(api-import): add security nets to catch up delays

.github/workflows/test.yml, README.md, docker-compose.yml, quotaclimat/data_processing/mediatree/api_import.py, quotaclimat/data_processing/mediatree/stop_word/main.py, quotaclimat/data_processing/mediatree/update_pg_keywords.py, test/sitemap/test_mediatree.py, test/sitemap/test_update_pg_keywords.py
FILTER_DAYS_STOP_WORD: default to 30 (days)
for update jobs after new stop words are added
=> perf: add FILTER_DAYS_STOP_WORD to get only the last stop words to speed up query

quotaclimat/data_processing/mediatree/channel_program.py, quotaclimat/data_processing/mediatree/detect_keywords.py, quotaclimat/data_processing/mediatree/s3/api_to_s3.py, quotaclimat/data_processing/mediatree/s3/s3_utils.py, test/sitemap/test_mediatree.py, test/stop_word/test_stop_word.py
Save using the right timezone (Europe/Paris) for now, instead of UTC
=> fix: save api data to specific timezone, default to europe/paris

my_dbt_project/models/dashboards/core_query_thematics_keywords.sql, my_dbt_project/pytest_tests/test_dbt_model_homepage.py, my_dbt_project/seeds/dictionary.csv, postgres/schemas/models.py
fix pour ces champs qui n'étaient pas cohérent quand plusieurs mots clés avec des attributs différents (un seul prenait le dessus sur les autres)
-     d.high_risk_of_false_positive,
d.solution,
d.consequence,
d.cause,
d.general_concepts,
d.statement,
d.crisis_climate,
d.crisis_biodiversity,
d.crisis_resource,
=> fix: dictionary table boolean value should have being compared

README.md, quotaclimat/data_processing/mediatree/api_import.py
Reenable CHANNEL env variable to specifify a channel to import for the mediatree-job
=> fix: use CHANNEL to specific a channel to import
